language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo g

after_script:
  - cp ./README.md ./public/
  - cd ./public
  - git init
  - git config user.name "${user_name}"
  - git config user.email "${user_email}"
  - git remote add origin https://${github_token}@${github_ref}
  - git add .
  - git commit -m "update"
  - git push -f -q origin master:master

branches:
  only:
    - develop
env:
 global:
   - github_ref: github.com/644262163/644262163.github.io.git